version: "3"
services:
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
  app:
    container_name: exhange-rate-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
    expose:
      - "3000"