version: "3"
services:
  app:
    container_name: exhange-rate-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
    expose:
      - "3000"   
    depends_on:
      - mysql   
  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:33060"
    expose:
      - "33060"